Deleted name context
tfycaf/dialogflow-bot pull request #2
Opened 2018-08-31 02:09 UTC by NelsonG-C

Should have the name context deleted from it this time.

2018-08-31 02:22 UTC, kanerogers requested changes

2018-08-31 02:22 UTC, kanerogers commented on chatbot.js
>    const { session } = request;
If this value isn't being used, why have it?

2018-08-31 02:22 UTC, kanerogers commented on chatbot.js
> -  return {
What should the return value for this function be?

2018-08-31 06:38 UTC, NelsonG-C commented on chatbot.js
>    const { session } = request;
Which value? I'm not sure what you are referring to?

2018-08-31 06:39 UTC, NelsonG-C commented on chatbot.js
> -  return {
does it need one?

2018-08-31 06:47 UTC, kanerogers commented on chatbot.js
>    const { session } = request;
Have a look at the line I'm commenting on 😄

2018-09-02 00:38 UTC, kanerogers commented on chatbot.js
> -  return {
What do you think? 🤔

2018-09-02 00:50 UTC, NelsonG-C commented on chatbot.js
>    const { session } = request;
Isn't request still being used to retrieve the PSID?

2018-09-02 00:51 UTC, NelsonG-C commented on chatbot.js
> -  return {
My thought is that it doesn't require a return because all we were returning was the output context for the name.

2018-09-02 00:56 UTC, NelsonG-C commented on chatbot.js
>    const { session } = request;
Oh actually, session doesn't look like it is being used for anything here. So it doesn't need to be there. What was session being used for previously?

2018-09-02 01:13 UTC, kanerogers commented on chatbot.js
>    const { session } = request;
No idea!

2018-09-02 01:13 UTC, kanerogers commented on chatbot.js
> -  return {
That sounds reasonable!

2018-09-02 01:14 UTC, kanerogers approved these changes

2018-09-02 01:14 UTC, kanerogers commented
@NelsonG-C LGTM - feel free to merge

2018-09-02 23:21 UTC, merged